// apps/vue-app/src/MicroApp.vue
<script>
import { h, onMounted, defineComponent, computed, onUpdated } from 'vue'

function loadScript(url) {
  return new Promise((resolve, reject) => {
    const script = document.createElement('script')
    script.src = url
    script.onload = resolve
    script.onerror = reject
    document.body.appendChild(script)
  })
}

export default defineComponent({
  name: 'MicroApp',
  props: {
    name: {
      type: String,
      required: true
    },
    url: {
      type: String,
      required: true
    }
  },
  setup(props) {
    const tagName = computed(() => props.name.split('_').join('-'))
    const fetchMicroApp = () => {
      if (!window[props.name]) {
        return loadScript(props.url)
          .then(() => window[props.name].get('./app'))
          .then((get) => get())
      }
      return Promise.resolve()
    }
    onMounted(() => fetchMicroApp())
    onUpdated(() => fetchMicroApp())
    return () => h(tagName.value)
  }
});
</script>

// apps/react-app/src/MicroApp.jsx
import { createElement, useEffect, useRef } from 'react'

function loadScript(url) {
  return new Promise((resolve, reject) => {
    const script = document.createElement('script')
    script.src = url
    script.onload = resolve
    script.onerror = reject
    document.body.appendChild(script)
  })
}

export default function MicroApp({ name, url }) {
  const tagName = name.split('_').join('-')
  const ref = useRef(null)
  useEffect(() => {
    if (!window[name]) {
      loadScript(url)
        .then(() => window[name].get('./app'))
        .then((get) => get())
    }
  }, [name, url])
  return createElement(tagName, { ref })
}
